

# initialization 
init:
	npm init 

# Install dependencies 
dependencies:
	yarn add fastify fastify-socket.io ioredis close-with-grace dotenv socket.io @fastify/cors 

# Install dev dependencies 
dev-dependencies:
	yarn add @types/node tsx typescript @types/ws -D

# create tsconfig.json 
tsconfig:
	yarn tsc --init 

# UI dependencies
ui-dependencies:
	yarn add socket.io-client 

# Add component 
shadcn-ui@latest add textarea button form

# Clean 
clean:
	rm ./build